"""
PRD data models for Professor v10.

Defines the structured data types used throughout the PRD clarification workflow:
- FeatureRequest: Raw feature input from a stakeholder
- ClarificationQuestion: A generated question requiring stakeholder input
- TechnicalConstraint: A resolved technical constraint from clarification
- AffectedComponent: A code component identified as potentially impacted
- StructuredPRD: The fully resolved PRD with all technical constraints

These models use Pydantic for validation and serialization, which enables
clean input/output contracts across the PRD clarification workflow.

See docs/design/04-prd-clarification-engine.md for the full workflow design.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class QuestionType(StrEnum):
    """
    The category of a clarification question.

    Used to organize questions in the clarification workflow and to ensure
    all critical technical dimensions are covered before finalizing the PRD.
    """

    CACHING = "CACHING"               # Cache impact: should this be cached? what TTL?
    CONSUMERS = "CONSUMERS"           # Who consumes this API or data?
    BACKWARD_COMPAT = "BACKWARD_COMPAT"  # Version compatibility requirements
    DATA_SOURCE = "DATA_SOURCE"       # Where does the data come from?
    SCOPE = "SCOPE"                   # Country, user segment, or feature scope
    SCHEMA = "SCHEMA"                 # Database schema change requirements
    ROLLOUT = "ROLLOUT"               # Deployment/rollout strategy
    FEATURE_FLAG = "FEATURE_FLAG"     # Feature flag requirements
    PERFORMANCE = "PERFORMANCE"       # Performance implications
    SECURITY = "SECURITY"             # Security/authorization requirements
    GENERAL = "GENERAL"               # General clarification needed


class ConstraintSource(StrEnum):
    """The origin of a technical constraint in the structured PRD."""

    CLARIFICATION_ANSWER = "clarification_answer"  # Provided by stakeholder
    GRAPH_INFERENCE = "graph_inference"             # Inferred from architecture graph
    CONVENTION = "convention"                       # Derived from existing system conventions
    MANUAL = "manual"                               # Manually specified in config


class ComponentRole(StrEnum):
    """The role of a code component in relation to the proposed change."""

    PRODUCES_DATA = "produces_data"       # Service that generates the new data
    EXPOSES_API = "exposes_api"           # Service/controller that exposes the API
    CONSUMES_API = "consumes_api"         # Service or frontend that calls the API
    OWNS_CONTRACT = "owns_contract"       # Service that owns the DTO/schema
    MAPS_FRONTEND = "maps_frontend"       # Frontend model that must be updated
    USES_CACHE = "uses_cache"             # Service that caches the affected data
    READS_DB = "reads_db"                 # Service that reads the affected database
    WRITES_DB = "writes_db"               # Service that writes the affected database
    CONSUMES_EVENTS = "consumes_events"   # Service that consumes affected Kafka events


class FeatureRequest(BaseModel):
    """
    The raw feature request as submitted by a stakeholder.

    This is the input to the PRD clarification workflow. It contains only
    what the stakeholder knows — business intent, user story, and any known
    constraints. The clarifier enriches this into a StructuredPRD.
    """

    title: str = Field(
        description="Short descriptive title for the feature.",
        examples=["Add estimated savings to coupon feed"],
    )

    description: str = Field(
        description="Full natural language description of the feature request.",
        examples=[
            "Add the estimated savings amount to the coupon feed for Indian users. "
            "This helps users understand how much they'll save before clicking."
        ],
    )

    requester: str | None = Field(
        default=None,
        description="Name or role of the person making the request (e.g., 'Product Manager - Coupons').",
    )

    priority: str = Field(
        default="medium",
        description="Business priority: 'critical', 'high', 'medium', 'low'.",
    )

    known_constraints: list[str] = Field(
        default_factory=list,
        description="Any constraints already known by the requester.",
        examples=[["India only", "Must not break existing app versions"]],
    )

    related_tickets: list[str] = Field(
        default_factory=list,
        description="Related JIRA tickets, GitHub issues, or other references.",
    )


class ClarificationQuestion(BaseModel):
    """
    A targeted clarification question generated by the PRD clarifier.

    Questions are generated based on:
    1. The feature description (what is being built)
    2. The architecture graph (what components are affected)
    3. Standard question templates (caching, compat, scope, etc.)

    Each question must be answered before the PRD can be finalized.
    """

    question_id: str = Field(description="Unique identifier for this question.")

    question_type: QuestionType = Field(
        description="The category of information this question is seeking."
    )

    text: str = Field(
        description="The full text of the clarification question.",
        examples=[
            "The feed response is currently cached with key `feed:{userId}:{country}` "
            "(TTL: 5 minutes). Should `estimatedSavings` be included in the cached "
            "response, or served fresh?"
        ],
    )

    is_required: bool = Field(
        default=True,
        description="Whether this question must be answered before the PRD is finalized.",
    )

    context: str = Field(
        default="",
        description="Evidence context explaining why this question was generated "
        "(e.g., which graph node triggered the question).",
    )

    graph_evidence: list[str] = Field(
        default_factory=list,
        description="Graph node IDs that informed this question's generation.",
    )

    answer: str | None = Field(
        default=None,
        description="The stakeholder's answer to this question (populated after clarification).",
    )

    is_answered: bool = Field(
        default=False,
        description="Whether this question has been answered.",
    )

    def mark_answered(self, answer: str) -> None:
        """Record the stakeholder's answer to this question."""
        self.answer = answer
        self.is_answered = True


class TechnicalConstraint(BaseModel):
    """
    A resolved technical constraint derived from the clarification process.

    Technical constraints form the core of the StructuredPRD — they are the
    specific, actionable technical requirements that engineers need to implement
    the feature correctly.
    """

    constraint_type: QuestionType = Field(
        description="The category of this technical constraint."
    )

    description: str = Field(
        description="Human-readable description of the constraint.",
        examples=["Field must be nullable; old app versions receive null"],
    )

    source: ConstraintSource = Field(
        description="How this constraint was determined."
    )

    raw_answer: str | None = Field(
        default=None,
        description="The original stakeholder answer this constraint was derived from.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional structured data for this constraint.",
        examples=[{"country": "IN", "ttl_seconds": 300}],
    )


class AffectedComponent(BaseModel):
    """
    A code component identified as potentially impacted by the proposed feature.

    AffectedComponents are identified by querying the architecture graph with
    the feature's domain entities. They feed into both the clarification
    question generation and the final impact report.
    """

    node_id: str = Field(
        description="The architecture graph node ID for this component.",
        examples=["coupon-engine/java/dto/CouponResponseDto"],
    )

    name: str = Field(
        description="Human-readable component name.",
        examples=["CouponResponseDto"],
    )

    component_type: str = Field(
        description="The entity type of the component (SERVICE, DTO, MODEL, etc.).",
    )

    repo: str = Field(
        description="Repository containing this component.",
        examples=["coupon-engine"],
    )

    language: str = Field(
        description="Programming language of this component.",
        examples=["java", "dart", "typescript"],
    )

    role: ComponentRole = Field(
        description="The role this component plays in the proposed change."
    )

    reason: str = Field(
        description="Why this component is identified as affected.",
        examples=["Directly contains the field being added"],
    )

    confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Confidence that this component is actually affected (0.0–1.0).",
    )


class StructuredPRD(BaseModel):
    """
    The fully resolved Product Requirements Document with technical constraints.

    This is the output of the PRD clarification workflow and the primary input
    to the change impact analysis and document generation steps.

    A StructuredPRD is considered complete when:
    - All required clarification questions have been answered
    - All technical constraints have been resolved
    - All affected components have been identified with sufficient confidence
    - The completeness_score is above the configured threshold
    """

    feature_id: str = Field(description="Unique identifier for this feature.")

    title: str = Field(description="Short title for the feature.")

    original_request: FeatureRequest = Field(
        description="The original raw feature request that was clarified."
    )

    technical_constraints: list[TechnicalConstraint] = Field(
        default_factory=list,
        description="Resolved technical constraints for this feature.",
    )

    affected_components: list[AffectedComponent] = Field(
        default_factory=list,
        description="Code components identified as potentially impacted.",
    )

    clarification_questions: list[ClarificationQuestion] = Field(
        default_factory=list,
        description="All clarification questions generated during the process.",
    )

    completeness_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description=(
            "Score from 0.0 to 1.0 representing how complete the PRD is. "
            "1.0 = all required questions answered and all constraints resolved. "
            "A score below 0.8 is considered incomplete."
        ),
    )

    missing_constraints: list[str] = Field(
        default_factory=list,
        description="Descriptions of technical constraints that are still missing.",
    )

    is_finalized: bool = Field(
        default=False,
        description="Whether this PRD has been finalized and is ready for impact analysis.",
    )

    @property
    def unanswered_questions(self) -> list[ClarificationQuestion]:
        """Return all required questions that have not yet been answered."""
        return [q for q in self.clarification_questions if q.is_required and not q.is_answered]

    @property
    def is_ready_for_analysis(self) -> bool:
        """
        Return True if the PRD is complete enough for impact analysis.

        A PRD is ready when:
        - All required clarification questions are answered
        - Completeness score is >= 0.8
        """
        return (
            len(self.unanswered_questions) == 0
            and self.completeness_score >= 0.8
        )

    def get_seed_node_ids(self) -> list[str]:
        """
        Return the graph node IDs of the directly affected components.

        These are used as seed nodes for the impact analysis traversal.
        Only returns high-confidence components (confidence >= 0.7).
        """
        return [
            c.node_id
            for c in self.affected_components
            if c.confidence >= 0.7
        ]
